In [1]:
from google.colab import drive
drive.mount('/content/gdrive', force_remount=True)

Mounted at /content/gdrive


In [2]:
path = '/content/gdrive/My Drive/NLP Engineer/Naive Bayes/PlayGolf/'
path

'/content/gdrive/My Drive/NLP Engineer/Naive Bayes/PlayGolf/'

## 1. Standardize our data

In [3]:
import pandas as pd

In [4]:
data = pd.read_excel(path + 'playgolf_data.xlsx', index_col=0)
data

Outlook Temperature Humidity    Wind Play Golf
Day                                                 
1       Sunny         Hot     High    Weak        No
2       Sunny         Hot     High  Strong        No
3    Overcast         Hot     High    Weak       Yes
4        Rain        Mild     High    Weak       Yes
5        Rain        Cool   Normal    Weak       Yes
6        Rain        Cool   Normal  Strong        No
7    Overcast        Cool   Normal  Strong       Yes
8       Sunny        Mild     High    Weak        No
9       Sunny        Cool   Normal    Weak       Yes
10       Rain        Mild   Normal    Weak       Yes
11      Sunny        Mild   Normal  Strong       Yes
12   Overcast        Mild     High  Strong       Yes
13   Overcast         Hot   Normal    Weak       Yes
14       Rain        Mild     High  Strong        No

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 14 entries, 1 to 14
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype 
---  ------       --------------  ----- 
 0   Outlook      14 non-null     object
 1   Temperature  14 non-null     object
 2   Humidity     14 non-null     object
 3   Wind         14 non-null     object
 4   Play Golf    14 non-null     object
dtypes: object(5)
memory usage: 672.0+ bytes


In [6]:
features = data.drop('Play Golf', axis=1)
target = data['Play Golf']

In [7]:
from sklearn.preprocessing import LabelEncoder

In [8]:
features = pd.get_dummies(features)
features

Outlook_Overcast  Outlook_Rain  ...  Wind_Strong  Wind_Weak
Day                                  ...                        
1                   0             0  ...            0          1
2                   0             0  ...            1          0
3                   1             0  ...            0          1
4                   0             1  ...            0          1
5                   0             1  ...            0          1
6                   0             1  ...            1          0
7                   1             0  ...            1          0
8                   0             0  ...            0          1
9                   0             0  ...            0          1
10                  0             1  ...            0          1
11                  0             0  ...            1          0
12                  1             0  ...            1          0
13                  1             0  ...            0          1
14                  0             1  ...            1          0

[14 rows x 10 columns]

In [9]:
target = LabelEncoder().fit_transform(target)
target

array([0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0])

## 2. Apply Naive Bayes

In [10]:
from sklearn.naive_bayes import GaussianNB

In [11]:
#Create a Gassian Classifier
model = GaussianNB()
model.fit(features, target)

GaussianNB(priors=None, var_smoothing=1e-09)

## 3. Check the Accuracy

In [12]:
import numpy as np
print("Prediction Accuracy is: ", model.score(features, target)*100, "%") #np.array(target)

Prediction Accuracy is:  64.28571428571429 %


>The percent of Accuracy is not high. Therefore, let us try another method by using BernoulliNB.



In [13]:
from sklearn.naive_bayes import BernoulliNB
model_ = BernoulliNB()
model_.fit(features, target)

BernoulliNB(alpha=1.0, binarize=0.0, class_prior=None, fit_prior=True)

In [14]:
print("Prediction Accuracy is: ", model_.score(features, target)*100, "%") #np.array(target)

Prediction Accuracy is:  92.85714285714286 %


In [15]:
model_.classes_

array([0, 1])

## 4. Save the Model

In [16]:
import pickle
pkl_playgolf = "playgolf_model.pkl" #filename
with open(pkl_playgolf, 'wb') as file:
  pickle.dump(model_, file)

## 5. Test

In [17]:
with open(pkl_playgolf, 'rb') as file:
  playgolf_model = pickle.load(file)

>for Testing:


>**X_test = [['Overcast', 'Cool', 'High', 'Strong'], ['Sunny', 'Cool', 'High', 'Weak']]**

In [18]:
X_test = [[1,0,0,1,0,0,1,0,1,0], [0,0,1,1,0,0,1,0,0,1]]
y_pred = playgolf_model.predict(X_test)
y_pred

array([1, 0])